//
// AppAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class AppAPI: APIBase {
    /**

     - parameter app: (query) app (optional)
     - parameter country: (query) country (optional)
     - parameter page: (query) A page number within the paginated result set. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func appSetupList(app app: String? = nil, country: String? = nil, page: Int32? = nil, completion: ((data: FlightInlineResponse2002?, error: ErrorType?) -> Void)) {
        appSetupListWithRequestBuilder(app: app, country: country, page: page).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     - GET /app/setup/
     - 
     - BASIC:
       - type: basic
       - name: Basic
     - examples: [{contentType=application/json, example={"empty": false}}]
     
     - parameter app: (query) app (optional)
     - parameter country: (query) country (optional)
     - parameter page: (query) A page number within the paginated result set. (optional)

     - returns: RequestBuilder<FlightInlineResponse2002> 
     */
    public class func appSetupListWithRequestBuilder(app app: String? = nil, country: String? = nil, page: Int32? = nil) -> RequestBuilder<FlightInlineResponse2002> {
        let path = "/app/setup/"
        let URLString = FlightSwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "app": app,
            "country": country,
            "page": page?.encodeToJSON()
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<FlightInlineResponse2002>.Type = FlightSwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
