//
// DeeplinkAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class DeeplinkAPI: APIBase {
    /**

     - parameter id: (path)  
     - parameter country: (query) Country code 
     - parameter legs: (query) Array of flight legs with date in YYYY-MM-DD format 
     - parameter cabinClass: (query) Cabin class like \&quot;economy\&quot;, \&quot;business\&quot; etc 
     - parameter adults: (query) Number of adults 
     - parameter currency: (query) Currency code to be used 
     - parameter language: (query) Preferred language 
     - parameter userId: (query) User id from MHD&#39;s server 
     - parameter appCode: (query) Unique code from backend for the project 
     - parameter childrenAges: (query) List of children ages (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deeplinkRead(id id: String, country: String, legs: [AnyObject], cabinClass: String, adults: Int32, currency: String, language: String, userId: String, appCode: String, childrenAges: [Int32]? = nil, completion: ((error: ErrorType?) -> Void)) {
        deeplinkReadWithRequestBuilder(id: id, country: country, legs: legs, cabinClass: cabinClass, adults: adults, currency: currency, language: language, userId: userId, appCode: appCode, childrenAges: childrenAges).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     - GET /deeplink/{id}/
     - Deeplink Generation
     - BASIC:
       - type: basic
       - name: Basic
     
     - parameter id: (path)  
     - parameter country: (query) Country code 
     - parameter legs: (query) Array of flight legs with date in YYYY-MM-DD format 
     - parameter cabinClass: (query) Cabin class like \&quot;economy\&quot;, \&quot;business\&quot; etc 
     - parameter adults: (query) Number of adults 
     - parameter currency: (query) Currency code to be used 
     - parameter language: (query) Preferred language 
     - parameter userId: (query) User id from MHD&#39;s server 
     - parameter appCode: (query) Unique code from backend for the project 
     - parameter childrenAges: (query) List of children ages (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func deeplinkReadWithRequestBuilder(id id: String, country: String, legs: [AnyObject], cabinClass: String, adults: Int32, currency: String, language: String, userId: String, appCode: String, childrenAges: [Int32]? = nil) -> RequestBuilder<Void> {
        var path = "/deeplink/{id}/"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = FlightSwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "country": country,
            "legs": legs,
            "cabin_class": cabinClass,
            "adults": adults.encodeToJSON(),
            "children_ages": childrenAges,
            "currency": currency,
            "language": language,
            "user_id": userId,
            "app_code": appCode
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = FlightSwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
