//
// DeeplinkAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class DeeplinkAPI {
    /**

     - parameter _id: (path)  
     - parameter country: (query) Country code 
     - parameter legs: (query) Array of flight legs with date in YYYY-MM-DD format 
     - parameter cabinClass: (query) Cabin class like \&quot;economy\&quot;, \&quot;business\&quot; etc 
     - parameter adults: (query) Number of adults 
     - parameter currency: (query) Currency code to be used 
     - parameter language: (query) Preferred language 
     - parameter userId: (query) User id from MHD&#39;s server 
     - parameter appCode: (query) Unique code from backend for the project 
     - parameter childrenAges: (query) List of children ages (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deeplinkRead(_id: String, country: String, legs: [FlightJSONValue], cabinClass: String, adults: Int, currency: String, language: String, userId: String, appCode: String, childrenAges: [Int]? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        deeplinkReadWithRequestBuilder(_id: _id, country: country, legs: legs, cabinClass: cabinClass, adults: adults, currency: currency, language: language, userId: userId, appCode: appCode, childrenAges: childrenAges).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - GET /deeplink/{id}/
     - Deeplink Generation
     - BASIC:
       - type: basic
       - name: Basic
     
     - parameter _id: (path)  
     - parameter country: (query) Country code 
     - parameter legs: (query) Array of flight legs with date in YYYY-MM-DD format 
     - parameter cabinClass: (query) Cabin class like \&quot;economy\&quot;, \&quot;business\&quot; etc 
     - parameter adults: (query) Number of adults 
     - parameter currency: (query) Currency code to be used 
     - parameter language: (query) Preferred language 
     - parameter userId: (query) User id from MHD&#39;s server 
     - parameter appCode: (query) Unique code from backend for the project 
     - parameter childrenAges: (query) List of children ages (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func deeplinkReadWithRequestBuilder(_id: String, country: String, legs: [FlightJSONValue], cabinClass: String, adults: Int, currency: String, language: String, userId: String, appCode: String, childrenAges: [Int]? = nil) -> RequestBuilder<Void> {
        var path = "/deeplink/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = FlightSwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "country": country, 
            "legs": legs, 
            "cabin_class": cabinClass, 
            "adults": adults.encodeToJSON(), 
            "children_ages": childrenAges, 
            "currency": currency, 
            "language": language, 
            "user_id": userId, 
            "app_code": appCode
        ])

        let requestBuilder: RequestBuilder<Void>.Type = FlightSwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
