//
// AircraftType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Aircraft information */
public class AircraftType: JSONEncodable {
    public var hex: String?
    public var regNumber: String?
    public var country: String?
    public var built: Int32?
    public var engine: String?
    public var engineCount: Int32?
    public var model: String?
    public var manufacturer: String?
    public var msn: String?
    public var type: String?
    public var category: String?
    public var line: String?
    public var imageUrl: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["hex"] = self.hex
        nillableDictionary["reg_number"] = self.regNumber
        nillableDictionary["country"] = self.country
        nillableDictionary["built"] = self.built?.encodeToJSON()
        nillableDictionary["engine"] = self.engine
        nillableDictionary["engine_count"] = self.engineCount?.encodeToJSON()
        nillableDictionary["model"] = self.model
        nillableDictionary["manufacturer"] = self.manufacturer
        nillableDictionary["msn"] = self.msn
        nillableDictionary["type"] = self.type
        nillableDictionary["category"] = self.category
        nillableDictionary["line"] = self.line
        nillableDictionary["image_url"] = self.imageUrl
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
