//
// AirlineFlightBoardResultModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class AirlineFlightBoardResultModel: JSONEncodable {
    public var departure: ScheduleListAirportType?
    public var arrival: ScheduleListAirportType?
    public var airline: ScheduleListAirlineType?
    public var flight: AirlineFlightBoardFlightType?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["departure"] = self.departure?.encodeToJSON()
        nillableDictionary["arrival"] = self.arrival?.encodeToJSON()
        nillableDictionary["airline"] = self.airline?.encodeToJSON()
        nillableDictionary["flight"] = self.flight?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
