//
// AirlineType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class AirlineType: JSONEncodable {
    public var name: String?
    public var iataCode: String?
    public var icaoCode: String?
    public var isInternational: Bool?
    public var website: String?
    public var country: String?
    public var callsign: String?
    public var isPassenger: Bool?
    public var isCargo: Bool?
    public var totalAircrafts: Int32?
    public var averageFleetAge: Double?
    public var accidentsLast5y: Int32?
    public var crashesLast5y: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["iata_code"] = self.iataCode
        nillableDictionary["icao_code"] = self.icaoCode
        nillableDictionary["is_international"] = self.isInternational
        nillableDictionary["website"] = self.website
        nillableDictionary["country"] = self.country
        nillableDictionary["callsign"] = self.callsign
        nillableDictionary["is_passenger"] = self.isPassenger
        nillableDictionary["is_cargo"] = self.isCargo
        nillableDictionary["total_aircrafts"] = self.totalAircrafts?.encodeToJSON()
        nillableDictionary["average_fleet_age"] = self.averageFleetAge
        nillableDictionary["accidents_last_5y"] = self.accidentsLast5y?.encodeToJSON()
        nillableDictionary["crashes_last_5y"] = self.crashesLast5y?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
