//
// Airport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Airport: JSONEncodable {
    public var iataCode: String?
    public var icaoCode: String?
    public var name: String?
    public var country: String?
    public var countryCode: String?
    public var isInternational: Bool?
    public var isMajor: Bool?
    public var city: String?
    public var location: String?
    public var timezone: Timezone?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["iata_code"] = self.iataCode
        nillableDictionary["icao_code"] = self.icaoCode
        nillableDictionary["name"] = self.name
        nillableDictionary["country"] = self.country
        nillableDictionary["country_code"] = self.countryCode
        nillableDictionary["is_international"] = self.isInternational
        nillableDictionary["is_major"] = self.isMajor
        nillableDictionary["city"] = self.city
        nillableDictionary["location"] = self.location
        nillableDictionary["timezone"] = self.timezone?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
