//
// AlertRequestModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class AlertRequestModel: JSONEncodable {
    /** User ID */
    public var user: String?
    /** Flight IATA code */
    public var flightIata: String?
    /** Date and time for the alert (ISO format) */
    public var date: NSDate?
    /** Departure airport IATA code */
    public var departureAirport: String?
    /** Arrival airport IATA code */
    public var arrivalAirport: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["user"] = self.user
        nillableDictionary["flight_iata"] = self.flightIata
        nillableDictionary["date"] = self.date?.encodeToJSON()
        nillableDictionary["departure_airport"] = self.departureAirport
        nillableDictionary["arrival_airport"] = self.arrivalAirport
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
