//
// Alert.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Alert: JSONEncodable {
    public var id: Int32?
    public var flightIata: String?
    public var date: NSDate?
    public var departureAirport: String?
    public var arrivalAirport: String?
    public var isActive: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["flight_iata"] = self.flightIata
        nillableDictionary["date"] = self.date?.encodeToJSON()
        nillableDictionary["departure_airport"] = self.departureAirport
        nillableDictionary["arrival_airport"] = self.arrivalAirport
        nillableDictionary["is_active"] = self.isActive
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
