//
// CombinedSearchResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CombinedSearchResult: JSONEncodable {
    public var type: String?
    public var iataCode: String?
    public var icaoCode: String?
    public var name: String?
    public var country: String?
    public var city: String?
    public var isInternational: Bool?
    public var isMajor: Bool?
    public var callsign: String?
    public var isPassenger: Bool?
    public var isCargo: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["type"] = self.type
        nillableDictionary["iata_code"] = self.iataCode
        nillableDictionary["icao_code"] = self.icaoCode
        nillableDictionary["name"] = self.name
        nillableDictionary["country"] = self.country
        nillableDictionary["city"] = self.city
        nillableDictionary["is_international"] = self.isInternational
        nillableDictionary["is_major"] = self.isMajor
        nillableDictionary["callsign"] = self.callsign
        nillableDictionary["is_passenger"] = self.isPassenger
        nillableDictionary["is_cargo"] = self.isCargo
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
