//
// FlightPriceInsightResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightPriceInsightResponseModel: JSONEncodable {
    public var priceStats: FlightPriceStatsModel?
    /** List of price quotes for different dates */
    public var results: [FlightPriceInsightQuoteModel]?
    public var currencyInfo: FlightCurrencyModelType?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["price_stats"] = self.priceStats?.encodeToJSON()
        nillableDictionary["results"] = self.results?.encodeToJSON()
        nillableDictionary["currency_info"] = self.currencyInfo?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
