//
// FlightProviderType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightProviderType: Codable {

    public var isSplit: Bool
    public var transferType: String?
    public var price: Double
    public var splitProviders: [FlightSplitProvider]

    public init(isSplit: Bool, transferType: String?, price: Double, splitProviders: [FlightSplitProvider]) {
        self.isSplit = isSplit
        self.transferType = transferType
        self.price = price
        self.splitProviders = splitProviders
    }


}

