//
// FlightPriceStatsModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Statistical information about prices */
public class FlightPriceStatsModel: JSONEncodable {
    /** Mean price across all dates */
    public var mean: Double?
    /** Standard deviation of prices */
    public var stdDev: Double?
    /** Lower threshold for categorization */
    public var lowerThreshold: Double?
    /** Upper threshold for categorization */
    public var upperThreshold: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["mean"] = self.mean
        nillableDictionary["std_dev"] = self.stdDev
        nillableDictionary["lower_threshold"] = self.lowerThreshold
        nillableDictionary["upper_threshold"] = self.upperThreshold
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
