//
// FlightAutocompleteItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightAutocompleteItem: JSONEncodable {
    public enum FlightType: String { 
        case Airport = "airport"
        case City = "city"
        case Country = "country"
    }
    /** IATA code of the airport */
    public var iataCode: String?
    /** Name of the airport */
    public var airportName: String?
    /** Type of the autocomplete item */
    public var type: FlightType?
    /** Name of the city if applicable */
    public var cityName: String?
    /** Display name for the item */
    public var displayName: String?
    /** Name of the country if applicable */
    public var countryName: String?
    /** Country code if applicable */
    public var countryCode: String?
    /** Image URL for the airport or city */
    public var imageUrl: String?
    public var coordinates: FlightCoordinate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["iataCode"] = self.iataCode
        nillableDictionary["airportName"] = self.airportName
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["cityName"] = self.cityName
        nillableDictionary["displayName"] = self.displayName
        nillableDictionary["countryName"] = self.countryName
        nillableDictionary["countryCode"] = self.countryCode
        nillableDictionary["imageUrl"] = self.imageUrl
        nillableDictionary["coordinates"] = self.coordinates?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
