//
// FlightDestinationResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightDestinationResponseModel: Codable {

    public var airport: FlightAirportResponseModel
    public var city: FlightCityResponseModel
    /** Departure date for exploration (YYYY-MM-DD) */
    public var departureDate: String
    /** Return date for exploration (YYYY-MM-DD) */
    public var returnDate: String
    public var flight: FlightFlightResponseModel
    /** List of languages */
    public var languages: [String]
    public var region: FlightRegionResponseModel
    /** Display name */
    public var displayName: String
    /** Number of days */
    public var days: Int

    public init(airport: FlightAirportResponseModel, city: FlightCityResponseModel, departureDate: String, returnDate: String, flight: FlightFlightResponseModel, languages: [String], region: FlightRegionResponseModel, displayName: String, days: Int) {
        self.airport = airport
        self.city = city
        self.departureDate = departureDate
        self.returnDate = returnDate
        self.flight = flight
        self.languages = languages
        self.region = region
        self.displayName = displayName
        self.days = days
    }

    public enum CodingKeys: String, CodingKey { 
        case airport
        case city
        case departureDate = "departure_date"
        case returnDate = "return_date"
        case flight
        case languages
        case region
        case displayName = "display_name"
        case days
    }


}

