//
// FlightFlightSearchResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightFlightSearchResponseModel: Codable {

    /** Search id from polling service */
    public var searchId: String
    /** Language of the response */
    public var language: String
    /** Currency of the response */
    public var currency: String
    /** Mode of the response, 1 - Kayak only, 2 - SkyScanner only, 3 - Kayak and SkyScanner */
    public var mode: Int
    public var currencyInfo: FlightCurrencyModelType?

    public init(searchId: String, language: String, currency: String, mode: Int, currencyInfo: FlightCurrencyModelType?) {
        self.searchId = searchId
        self.language = language
        self.currency = currency
        self.mode = mode
        self.currencyInfo = currencyInfo
    }

    public enum CodingKeys: String, CodingKey { 
        case searchId = "search_id"
        case language
        case currency
        case mode
        case currencyInfo = "currency_info"
    }


}

