//
// FlightFlightSearchResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightFlightSearchResponseModel: JSONEncodable {
    /** Search id from polling service */
    public var searchId: String?
    /** Language of the response */
    public var language: String?
    /** Currency of the response */
    public var currency: String?
    /** Mode of the response, 1 - Kayak only, 2 - SkyScanner only, 3 - Kayak and SkyScanner */
    public var mode: Int32?
    public var currencyInfo: FlightCurrencyModelType?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["search_id"] = self.searchId
        nillableDictionary["language"] = self.language
        nillableDictionary["currency"] = self.currency
        nillableDictionary["mode"] = self.mode?.encodeToJSON()
        nillableDictionary["currency_info"] = self.currencyInfo?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
