//
// FlightPriceInsightQuoteModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightPriceInsightQuoteModel: JSONEncodable {
    /** Date timestamp */
    public var date: Int32?
    /** Price in the requested currency */
    public var price: Double?
    /** Currency code */
    public var currency: String?
    public var outbound: FlightFlightLegModel?
    public var inbound: FlightFlightLegModel?
    /** Price category: cheap, normal, or expensive */
    public var priceCategory: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["date"] = self.date?.encodeToJSON()
        nillableDictionary["price"] = self.price
        nillableDictionary["currency"] = self.currency
        nillableDictionary["outbound"] = self.outbound?.encodeToJSON()
        nillableDictionary["inbound"] = self.inbound?.encodeToJSON()
        nillableDictionary["price_category"] = self.priceCategory
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
