//
// FlightAirlineFilterData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightAirlineFilterData: Codable {

    public var airlineName: String
    public var airlineIata: String
    public var airlineLogo: String

    public init(airlineName: String, airlineIata: String, airlineLogo: String) {
        self.airlineName = airlineName
        self.airlineIata = airlineIata
        self.airlineLogo = airlineLogo
    }


}

