//
// FlightFlightDetailModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of the cheapest flight */

public struct FlightFlightDetailModel: Codable {

    /** Price of the flight */
    public var price: Double
    /** Duration of the flight in minutes */
    public var duration: Int

    public init(price: Double, duration: Int) {
        self.price = price
        self.duration = duration
    }


}

