//
// FlightPriceStatsModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Statistical information about prices */

public struct FlightPriceStatsModel: Codable {

    /** Mean price across all dates */
    public var mean: Double
    /** Standard deviation of prices */
    public var stdDev: Double
    /** Lower threshold for categorization */
    public var lowerThreshold: Double
    /** Upper threshold for categorization */
    public var upperThreshold: Double

    public init(mean: Double, stdDev: Double, lowerThreshold: Double, upperThreshold: Double) {
        self.mean = mean
        self.stdDev = stdDev
        self.lowerThreshold = lowerThreshold
        self.upperThreshold = upperThreshold
    }

    public enum CodingKeys: String, CodingKey { 
        case mean
        case stdDev = "std_dev"
        case lowerThreshold = "lower_threshold"
        case upperThreshold = "upper_threshold"
    }


}

