//
// FlightExploreResponseItemModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightExploreResponseItemModel: Codable {

    /** Price */
    public var price: Double
    public var location: FlightExploreResponseItemLocationModel
    /** Is direct flight */
    public var isDirect: Bool

    public init(price: Double, location: FlightExploreResponseItemLocationModel, isDirect: Bool) {
        self.price = price
        self.location = location
        self.isDirect = isDirect
    }

    public enum CodingKeys: String, CodingKey { 
        case price
        case location
        case isDirect = "is_direct"
    }


}

