//
// FlightAirportModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Origin airport details */
public class FlightAirportModel: JSONEncodable {
    /** IATA code of the airport */
    public var iata: String?
    /** Name of the airport */
    public var name: String?
    /** Country of the airport */
    public var country: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["iata"] = self.iata
        nillableDictionary["name"] = self.name
        nillableDictionary["country"] = self.country
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
