//
// FlightCountryResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightCountryResponseModel: JSONEncodable {
    /** Country ID */
    public var id: String?
    /** Country name */
    public var name: String?
    /** Country code */
    public var shortName: String?
    /** Country latitude */
    public var latitude: Double?
    /** Country longitude */
    public var longitude: Double?
    /** List of destinations */
    public var destinations: [FlightDestinationResponseModel]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["short_name"] = self.shortName
        nillableDictionary["latitude"] = self.latitude
        nillableDictionary["longitude"] = self.longitude
        nillableDictionary["destinations"] = self.destinations?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
