//
// FlightFlight.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightFlight: JSONEncodable {
    public var id: String?
    public var totalDuration: Int32?
    public var minPrice: Double?
    public var maxPrice: Double?
    public var legs: [FlightLeg]?
    public var providers: [FlightProviderType]?
    public var isBest: Bool?
    public var isCheapest: Bool?
    public var isFastest: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["total_duration"] = self.totalDuration?.encodeToJSON()
        nillableDictionary["min_price"] = self.minPrice
        nillableDictionary["max_price"] = self.maxPrice
        nillableDictionary["legs"] = self.legs?.encodeToJSON()
        nillableDictionary["providers"] = self.providers?.encodeToJSON()
        nillableDictionary["is_best"] = self.isBest
        nillableDictionary["is_cheapest"] = self.isCheapest
        nillableDictionary["is_fastest"] = self.isFastest
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
