//
// FlightPollRequestBodyModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightPollRequestBodyModel: Codable {

    public enum FlightSortBy: String, Codable { 
        case duration = "duration"
        case price = "price"
    }
    public enum FlightSortOrder: String, Codable { 
        case asc = "asc"
        case desc = "desc"
    }
    /** Maximum duration of the flight in minutes */
    public var durationMax: Int?
    /** Maximum stop count of the flight */
    public var stopCountMax: Int?
    /** List of arrival/departure ranges */
    public var arrivalDepartureRanges: [FlightArrivalDeparture]?
    /** List of IATA codes to exclude */
    public var iataCodesExclude: [String]?
    /** List of IATA codes to include */
    public var iataCodesInclude: [String]?
    /** Field to sort by */
    public var sortBy: FlightSortBy?
    /** Order of sorting */
    public var sortOrder: FlightSortOrder?
    /** List of agencies to exclude */
    public var agencyExclude: [String]?
    /** List of agencies to include */
    public var agencyInclude: [String]?
    /** Minimum price for filtering flights */
    public var priceMin: Double?
    /** Maximum price for filtering flights */
    public var priceMax: Double?

    public init(durationMax: Int?, stopCountMax: Int?, arrivalDepartureRanges: [FlightArrivalDeparture]?, iataCodesExclude: [String]?, iataCodesInclude: [String]?, sortBy: FlightSortBy?, sortOrder: FlightSortOrder?, agencyExclude: [String]?, agencyInclude: [String]?, priceMin: Double?, priceMax: Double?) {
        self.durationMax = durationMax
        self.stopCountMax = stopCountMax
        self.arrivalDepartureRanges = arrivalDepartureRanges
        self.iataCodesExclude = iataCodesExclude
        self.iataCodesInclude = iataCodesInclude
        self.sortBy = sortBy
        self.sortOrder = sortOrder
        self.agencyExclude = agencyExclude
        self.agencyInclude = agencyInclude
        self.priceMin = priceMin
        self.priceMax = priceMax
    }

    public enum CodingKeys: String, CodingKey { 
        case durationMax = "duration_max"
        case stopCountMax = "stop_count_max"
        case arrivalDepartureRanges = "arrival_departure_ranges"
        case iataCodesExclude = "iata_codes_exclude"
        case iataCodesInclude = "iata_codes_include"
        case sortBy = "sort_by"
        case sortOrder = "sort_order"
        case agencyExclude = "agency_exclude"
        case agencyInclude = "agency_include"
        case priceMin = "price_min"
        case priceMax = "price_max"
    }


}

