//
// FlightFlightSearchRequestBodyModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightFlightSearchRequestBodyModel: Codable {

    /** List of flight legs */
    public var legs: [FlightLegType]
    /** Cabin class like \&quot;economy\&quot;, \&quot;business\&quot; etc */
    public var cabinClass: String
    /** Number of adults */
    public var adults: Int
    /** List of children ages */
    public var childrenAges: [Int]

    public init(legs: [FlightLegType], cabinClass: String, adults: Int, childrenAges: [Int]) {
        self.legs = legs
        self.cabinClass = cabinClass
        self.adults = adults
        self.childrenAges = childrenAges
    }

    public enum CodingKeys: String, CodingKey { 
        case legs
        case cabinClass = "cabin_class"
        case adults
        case childrenAges = "children_ages"
    }


}

