//
// FlightAirlineModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Airline details */
public class FlightAirlineModel: JSONEncodable {
    /** IATA code of the airline */
    public var iata: String?
    /** Name of the airline */
    public var name: String?
    /** URL to the airline logo */
    public var logo: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["iata"] = self.iata
        nillableDictionary["name"] = self.name
        nillableDictionary["logo"] = self.logo
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
