//
// FlightLegType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightLegType: Codable {

    /** Origin airport code like \&quot;SFO\&quot; */
    public var origin: String
    /** Destination airport code like \&quot;LAX\&quot; */
    public var destination: String
    /** Date in YYYY-MM-DD format */
    public var date: String

    public init(origin: String, destination: String, date: String) {
        self.origin = origin
        self.destination = destination
        self.date = date
    }


}

