//
// FlightFlightResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Flight details */
public class FlightFlightResponseModel: JSONEncodable {
    public var price: Double?
    public var priceFormatted: String?
    public var airline: String?
    public var airlineCode: String?
    public var maxStops: Int32?
    public var maxDuration: Int32?
    public var shareUrl: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["price"] = self.price
        nillableDictionary["price_formatted"] = self.priceFormatted
        nillableDictionary["airline"] = self.airline
        nillableDictionary["airline_code"] = self.airlineCode
        nillableDictionary["max_stops"] = self.maxStops?.encodeToJSON()
        nillableDictionary["max_duration"] = self.maxDuration?.encodeToJSON()
        nillableDictionary["share_url"] = self.shareUrl
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
