//
// FlightFlightDetailModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Details of the cheapest flight */
public class FlightFlightDetailModel: JSONEncodable {
    /** Price of the flight */
    public var price: Double?
    /** Duration of the flight in minutes */
    public var duration: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["price"] = self.price
        nillableDictionary["duration"] = self.duration?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
