//
// FlightSegment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightSegment: JSONEncodable {
    public var id: String?
    public var arriveTimeAirport: Int32?
    public var departureTimeAirport: Int32?
    public var duration: Int32?
    public var flightNumber: String?
    public var airlineName: String?
    public var airlineIata: String?
    public var airlineLogo: String?
    public var originCode: String?
    public var origin: String?
    public var destinationCode: String?
    public var destination: String?
    public var arrivalDayDifference: Int32?
    public var wifi: Bool?
    public var cabinClass: String?
    public var aircraft: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["arriveTimeAirport"] = self.arriveTimeAirport?.encodeToJSON()
        nillableDictionary["departureTimeAirport"] = self.departureTimeAirport?.encodeToJSON()
        nillableDictionary["duration"] = self.duration?.encodeToJSON()
        nillableDictionary["flightNumber"] = self.flightNumber
        nillableDictionary["airlineName"] = self.airlineName
        nillableDictionary["airlineIata"] = self.airlineIata
        nillableDictionary["airlineLogo"] = self.airlineLogo
        nillableDictionary["originCode"] = self.originCode
        nillableDictionary["origin"] = self.origin
        nillableDictionary["destinationCode"] = self.destinationCode
        nillableDictionary["destination"] = self.destination
        nillableDictionary["arrival_day_difference"] = self.arrivalDayDifference?.encodeToJSON()
        nillableDictionary["wifi"] = self.wifi
        nillableDictionary["cabinClass"] = self.cabinClass
        nillableDictionary["aircraft"] = self.aircraft
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
