//
// FlightAlertRoute.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightAlertRoute: JSONEncodable {
    public var id: Int32?
    public var origin: String?
    public var destination: String?
    public var departureDate: FlightISOFullDate?
    public var returnDate: FlightISOFullDate?
    public var currency: String?
    public var currentPrice: Int32?
    public var lastNotifiedPrice: Int32?
    public var createdAt: NSDate?
    public var updatedAt: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["origin"] = self.origin
        nillableDictionary["destination"] = self.destination
        nillableDictionary["departure_date"] = self.departureDate?.encodeToJSON()
        nillableDictionary["return_date"] = self.returnDate?.encodeToJSON()
        nillableDictionary["currency"] = self.currency
        nillableDictionary["current_price"] = self.currentPrice?.encodeToJSON()
        nillableDictionary["last_notified_price"] = self.lastNotifiedPrice?.encodeToJSON()
        nillableDictionary["created_at"] = self.createdAt?.encodeToJSON()
        nillableDictionary["updated_at"] = self.updatedAt?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
