//
// FlightRegionResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Region details */

public struct FlightRegionResponseModel: Codable {

    public var _id: String?
    public var name: String?
    public var shortName: String?
    public var latitude: Double?
    public var longitude: Double?

    public init(_id: String?, name: String?, shortName: String?, latitude: Double?, longitude: Double?) {
        self._id = _id
        self.name = name
        self.shortName = shortName
        self.latitude = latitude
        self.longitude = longitude
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case shortName = "short_name"
        case latitude
        case longitude
    }


}

