//
// FlightInlineResponse2001.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightInlineResponse2001: Codable {

    public var count: Int
    public var next: String?
    public var previous: String?
    public var results: [FlightCurrency]

    public init(count: Int, next: String?, previous: String?, results: [FlightCurrency]) {
        self.count = count
        self.next = next
        self.previous = previous
        self.results = results
    }


}

