//
// FlightExploreResponseItemModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightExploreResponseItemModel: JSONEncodable {
    /** Price */
    public var price: Double?
    public var location: FlightExploreResponseItemLocationModel?
    /** Is direct flight */
    public var isDirect: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["price"] = self.price
        nillableDictionary["location"] = self.location?.encodeToJSON()
        nillableDictionary["is_direct"] = self.isDirect
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
