//
// FlightAutocompleteResponseBodyModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightAutocompleteResponseBodyModel: Codable {

    /** List of autocomplete items */
    public var data: [FlightAutocompleteItem]
    /** Language of the response */
    public var language: String?

    public init(data: [FlightAutocompleteItem], language: String?) {
        self.data = data
        self.language = language
    }


}

