//
// FlightDestinationResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightDestinationResponseModel: JSONEncodable {
    public var airport: FlightAirportResponseModel?
    public var city: FlightCityResponseModel?
    /** Departure date for exploration (YYYY-MM-DD) */
    public var departureDate: String?
    /** Return date for exploration (YYYY-MM-DD) */
    public var returnDate: String?
    public var flight: FlightFlightResponseModel?
    /** List of languages */
    public var languages: [String]?
    public var region: FlightRegionResponseModel?
    /** Display name */
    public var displayName: String?
    /** Number of days */
    public var days: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["airport"] = self.airport?.encodeToJSON()
        nillableDictionary["city"] = self.city?.encodeToJSON()
        nillableDictionary["departure_date"] = self.departureDate
        nillableDictionary["return_date"] = self.returnDate
        nillableDictionary["flight"] = self.flight?.encodeToJSON()
        nillableDictionary["languages"] = self.languages?.encodeToJSON()
        nillableDictionary["region"] = self.region?.encodeToJSON()
        nillableDictionary["display_name"] = self.displayName
        nillableDictionary["days"] = self.days?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
