//
// FlightPriceInsightQuoteModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightPriceInsightQuoteModel: Codable {

    /** Date timestamp */
    public var date: Int
    /** Price in the requested currency */
    public var price: Double
    /** Currency code */
    public var currency: String
    public var outbound: FlightFlightLegModel
    public var inbound: FlightFlightLegModel?
    /** Price category: cheap, normal, or expensive */
    public var priceCategory: String?

    public init(date: Int, price: Double, currency: String, outbound: FlightFlightLegModel, inbound: FlightFlightLegModel?, priceCategory: String?) {
        self.date = date
        self.price = price
        self.currency = currency
        self.outbound = outbound
        self.inbound = inbound
        self.priceCategory = priceCategory
    }

    public enum CodingKeys: String, CodingKey { 
        case date
        case price
        case currency
        case outbound
        case inbound
        case priceCategory = "price_category"
    }


}

