//
// FlightCurrencyModelType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Currency details */
public class FlightCurrencyModelType: JSONEncodable {
    /** Currency code */
    public var code: String?
    /** Currency symbol */
    public var symbol: String?
    /** Thousands separator */
    public var thousandsSeparator: String?
    /** Decimal separator */
    public var decimalSeparator: String?
    /** Symbol on left */
    public var symbolOnLeft: Bool?
    /** Space between amount and symbol */
    public var spaceBetweenAmountAndSymbol: Bool?
    /** Decimal digits */
    public var decimalDigits: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["code"] = self.code
        nillableDictionary["symbol"] = self.symbol
        nillableDictionary["thousands_separator"] = self.thousandsSeparator
        nillableDictionary["decimal_separator"] = self.decimalSeparator
        nillableDictionary["symbol_on_left"] = self.symbolOnLeft
        nillableDictionary["space_between_amount_and_symbol"] = self.spaceBetweenAmountAndSymbol
        nillableDictionary["decimal_digits"] = self.decimalDigits?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
