//
// FlightAirportModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Origin airport details */

public struct FlightAirportModel: Codable {

    /** IATA code of the airport */
    public var iata: String
    /** Name of the airport */
    public var name: String
    /** Country of the airport */
    public var country: String

    public init(iata: String, name: String, country: String) {
        self.iata = iata
        self.name = name
        self.country = country
    }


}

