//
// FlightExploreResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightExploreResponseModel: Codable {

    public var origin: FlightOriginResponseModel
    /** Countries with their destinations */
    public var countries: [FlightCountryResponseModel]

    public init(origin: FlightOriginResponseModel, countries: [FlightCountryResponseModel]) {
        self.origin = origin
        self.countries = countries
    }


}

