//
// FlightArrivalDeparture.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightArrivalDeparture: Codable {

    public var arrival: FlightTimeRange?
    public var departure: FlightTimeRange?

    public init(arrival: FlightTimeRange?, departure: FlightTimeRange?) {
        self.arrival = arrival
        self.departure = departure
    }


}

