//
// FlightInfoAirport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Departure information */
public class FlightInfoAirport: JSONEncodable {
    public var airport: Airport?
    public var scheduled: FlightDatetimeDataType?
    public var estimated: FlightDatetimeDataType?
    public var taxiing: FlightDatetimeDataType?
    public var actual: FlightDatetimeDataType?
    public var terminal: String?
    public var gate: String?
    public var baggageBelt: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["airport"] = self.airport?.encodeToJSON()
        nillableDictionary["scheduled"] = self.scheduled?.encodeToJSON()
        nillableDictionary["estimated"] = self.estimated?.encodeToJSON()
        nillableDictionary["taxiing"] = self.taxiing?.encodeToJSON()
        nillableDictionary["actual"] = self.actual?.encodeToJSON()
        nillableDictionary["terminal"] = self.terminal
        nillableDictionary["gate"] = self.gate
        nillableDictionary["baggage_belt"] = self.baggageBelt
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
