//
// FlightInlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightInlineResponse200: Codable {

    public var count: Int
    public var next: String?
    public var previous: String?
    public var results: [FlightCountry]

    public init(count: Int, next: String?, previous: String?, results: [FlightCountry]) {
        self.count = count
        self.next = next
        self.previous = previous
        self.results = results
    }


}

