//
// FlightDatetimeDataType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightDatetimeDataType: JSONEncodable {
    public var utc: NSDate?
    public var local: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["utc"] = self.utc?.encodeToJSON()
        nillableDictionary["local"] = self.local?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
