//
// FlightFlight.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightFlight: Codable {

    public var _id: String
    public var totalDuration: Int
    public var minPrice: Double
    public var maxPrice: Double
//    public var legs: [FlightLeg]
//    public var providers: [FlightProviderType]
    public var isBest: Bool?
    public var isCheapest: Bool?
    public var isFastest: Bool?

    public init(_id: String, totalDuration: Int, minPrice: Double, maxPrice: Double, isBest: Bool?, isCheapest: Bool?, isFastest: Bool?) {
        self._id = _id
        self.totalDuration = totalDuration
        self.minPrice = minPrice
        self.maxPrice = maxPrice
//        self.legs = legs
//        self.providers = providers
        self.isBest = isBest
        self.isCheapest = isCheapest
        self.isFastest = isFastest
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case totalDuration = "total_duration"
        case minPrice = "min_price"
        case maxPrice = "max_price"
        case isBest = "is_best"
        case isCheapest = "is_cheapest"
        case isFastest = "is_fastest"
    }


}

