//
// FlightLeg.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightLeg: Codable {

    public var arriveTimeAirport: Int
    public var departureTimeAirport: Int
    public var duration: Int
    public var origin: String
    public var originCode: String
    public var destination: String
    public var destinationCode: String
    public var stopCount: Int
    public var segments: [FlightSegment]

    public init(arriveTimeAirport: Int, departureTimeAirport: Int, duration: Int, origin: String, originCode: String, destination: String, destinationCode: String, stopCount: Int, segments: [FlightSegment]) {
        self.arriveTimeAirport = arriveTimeAirport
        self.departureTimeAirport = departureTimeAirport
        self.duration = duration
        self.origin = origin
        self.originCode = originCode
        self.destination = destination
        self.destinationCode = destinationCode
        self.stopCount = stopCount
        self.segments = segments
    }


}

