//
// FlightSplitProvider.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightSplitProvider: Codable {

    public var name: String
    public var imageURL: String
    public var price: Double
    public var deeplink: String
    public var rating: Double?
    public var ratingCount: Int?
//    public var fareFamily: [String:String]?

    public init(name: String, imageURL: String, price: Double, deeplink: String, rating: Double?, ratingCount: Int?) {
        self.name = name
        self.imageURL = imageURL
        self.price = price
        self.deeplink = deeplink
        self.rating = rating
        self.ratingCount = ratingCount
//        self.fareFamily = fareFamily
    }


}

