//
// FlightCurrencyModelType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Currency information for formatting prices */

public struct FlightCurrencyModelType: Codable {

    /** Currency code */
    public var code: String
    /** Currency symbol */
    public var symbol: String
    /** Thousands separator */
    public var thousandsSeparator: String
    /** Decimal separator */
    public var decimalSeparator: String
    /** Symbol on left */
    public var symbolOnLeft: Bool
    /** Space between amount and symbol */
    public var spaceBetweenAmountAndSymbol: Bool
    /** Decimal digits */
    public var decimalDigits: Int

    public init(code: String, symbol: String, thousandsSeparator: String, decimalSeparator: String, symbolOnLeft: Bool, spaceBetweenAmountAndSymbol: Bool, decimalDigits: Int) {
        self.code = code
        self.symbol = symbol
        self.thousandsSeparator = thousandsSeparator
        self.decimalSeparator = decimalSeparator
        self.symbolOnLeft = symbolOnLeft
        self.spaceBetweenAmountAndSymbol = spaceBetweenAmountAndSymbol
        self.decimalDigits = decimalDigits
    }

    public enum CodingKeys: String, CodingKey { 
        case code
        case symbol
        case thousandsSeparator = "thousands_separator"
        case decimalSeparator = "decimal_separator"
        case symbolOnLeft = "symbol_on_left"
        case spaceBetweenAmountAndSymbol = "space_between_amount_and_symbol"
        case decimalDigits = "decimal_digits"
    }


}

