//
// FlightCountryResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightCountryResponseModel: Codable {

    /** Country ID */
    public var _id: String
    /** Country name */
    public var name: String
    /** Country code */
    public var shortName: String
    /** Country latitude */
    public var latitude: Double
    /** Country longitude */
    public var longitude: Double
    /** List of destinations */
    public var destinations: [FlightDestinationResponseModel]

    public init(_id: String, name: String, shortName: String, latitude: Double, longitude: Double, destinations: [FlightDestinationResponseModel]) {
        self._id = _id
        self.name = name
        self.shortName = shortName
        self.latitude = latitude
        self.longitude = longitude
        self.destinations = destinations
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case shortName = "short_name"
        case latitude
        case longitude
        case destinations
    }


}

