//
// FlightFlightResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Flight details */

public struct FlightFlightResponseModel: Codable {

    public var price: Double
    public var priceFormatted: String
    public var airline: String
    public var airlineCode: String
    public var maxStops: Int
    public var maxDuration: Int
    public var shareUrl: String

    public init(price: Double, priceFormatted: String, airline: String, airlineCode: String, maxStops: Int, maxDuration: Int, shareUrl: String) {
        self.price = price
        self.priceFormatted = priceFormatted
        self.airline = airline
        self.airlineCode = airlineCode
        self.maxStops = maxStops
        self.maxDuration = maxDuration
        self.shareUrl = shareUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case price
        case priceFormatted = "price_formatted"
        case airline
        case airlineCode = "airline_code"
        case maxStops = "max_stops"
        case maxDuration = "max_duration"
        case shareUrl = "share_url"
    }


}

