//
// FlightLegType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightLegType: JSONEncodable {
    /** Origin airport code like \&quot;SFO\&quot; */
    public var origin: String?
    /** Destination airport code like \&quot;LAX\&quot; */
    public var destination: String?
    /** Date in YYYY-MM-DD format */
    public var date: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["origin"] = self.origin
        nillableDictionary["destination"] = self.destination
        nillableDictionary["date"] = self.date
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
