//
// FlightFlightLegModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Outbound flight details */

public struct FlightFlightLegModel: Codable {

    public var origin: FlightAirportModel
    public var destination: FlightAirportModel
    public var airline: FlightAirlineModel
    /** Departure timestamp */
    public var departure: Int
    /** Whether the flight is direct */
    public var direct: Bool

    public init(origin: FlightAirportModel, destination: FlightAirportModel, airline: FlightAirlineModel, departure: Int, direct: Bool) {
        self.origin = origin
        self.destination = destination
        self.airline = airline
        self.departure = departure
        self.direct = direct
    }


}

