//
// FlightAirportResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Airport details */
public class FlightAirportResponseModel: JSONEncodable {
    public var name: String?
    public var shortName: String?
    public var popularity: Int32?
    public var latitude: Double?
    public var longitude: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["short_name"] = self.shortName
        nillableDictionary["popularity"] = self.popularity?.encodeToJSON()
        nillableDictionary["latitude"] = self.latitude
        nillableDictionary["longitude"] = self.longitude
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
