//
// FlightExploreResponseItemLocationModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Location details */
public class FlightExploreResponseItemLocationModel: JSONEncodable {
    /** Entity ID */
    public var entityId: String?
    /** Entity name */
    public var name: String?
    /** Entity IATA code */
    public var iata: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["entityId"] = self.entityId
        nillableDictionary["name"] = self.name
        nillableDictionary["iata"] = self.iata
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
