//
// FlightInfoResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightInfoResponseModel: JSONEncodable {
    public var greatCircleDistance: GreatCircleDistance?
    public var departure: FlightInfoAirport?
    public var arrival: FlightInfoAirport?
    /** Last updated timestamp */
    public var lastUpdated: NSDate?
    /** Flight IATA code */
    public var flightIata: String?
    /** Call sign */
    public var callSign: String?
    /** Flight status */
    public var status: String?
    /** Codeshare status */
    public var codeshareStatus: String?
    /** Is cargo flight */
    public var isCargo: Bool?
    public var aircraft: AircraftType?
    public var airline: AirlineType?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["great_circle_distance"] = self.greatCircleDistance?.encodeToJSON()
        nillableDictionary["departure"] = self.departure?.encodeToJSON()
        nillableDictionary["arrival"] = self.arrival?.encodeToJSON()
        nillableDictionary["last_updated"] = self.lastUpdated?.encodeToJSON()
        nillableDictionary["flight_iata"] = self.flightIata
        nillableDictionary["call_sign"] = self.callSign
        nillableDictionary["status"] = self.status
        nillableDictionary["codeshare_status"] = self.codeshareStatus
        nillableDictionary["is_cargo"] = self.isCargo
        nillableDictionary["aircraft"] = self.aircraft?.encodeToJSON()
        nillableDictionary["airline"] = self.airline?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
