//
// FlightAirlineModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Airline details */

public struct FlightAirlineModel: Codable {

    /** IATA code of the airline */
    public var iata: String
    /** Name of the airline */
    public var name: String
    /** URL to the airline logo */
    public var logo: String

    public init(iata: String, name: String, logo: String) {
        self.iata = iata
        self.name = name
        self.logo = logo
    }


}

