//
// FlightPollResponseBodyModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightPollResponseBodyModel: JSONEncodable {
    /** Number of flights available in cache */
    public var count: Int32?
    /** Link to next page but use page param instead */
    public var next: String?
    /** Link to previous page but use page param instead */
    public var previous: String?
    /** Cache status, True if polling is complete */
    public var cache: Bool?
    /** Number of passengers */
    public var passengerCount: Int32?
    /** List of airlines */
    public var airlines: [FlightAirlineFilterData]?
    /** Minimum duration of the flight in minutes */
    public var minDuration: Int32?
    /** Maximum duration of the flight in minutes */
    public var maxDuration: Int32?
    /** List of agencies */
    public var agencies: [FlightProviderFilterData]?
    public var cheapestFlight: FlightFlightDetailModel?
    public var bestFlight: FlightFlightDetailModel?
    public var fastestFlight: FlightFlightDetailModel?
    /** List of flights */
    public var results: [FlightFlight]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["count"] = self.count?.encodeToJSON()
        nillableDictionary["next"] = self.next
        nillableDictionary["previous"] = self.previous
        nillableDictionary["cache"] = self.cache
        nillableDictionary["passenger_count"] = self.passengerCount?.encodeToJSON()
        nillableDictionary["airlines"] = self.airlines?.encodeToJSON()
        nillableDictionary["min_duration"] = self.minDuration?.encodeToJSON()
        nillableDictionary["max_duration"] = self.maxDuration?.encodeToJSON()
        nillableDictionary["agencies"] = self.agencies?.encodeToJSON()
        nillableDictionary["cheapest_flight"] = self.cheapestFlight?.encodeToJSON()
        nillableDictionary["best_flight"] = self.bestFlight?.encodeToJSON()
        nillableDictionary["fastest_flight"] = self.fastestFlight?.encodeToJSON()
        nillableDictionary["results"] = self.results?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
