//
// FlightAutocompleteItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightAutocompleteItem: Codable {

    public enum FlightType: String, Codable { 
        case airport = "airport"
        case city = "city"
        case country = "country"
    }
    /** IATA code of the airport */
    public var iataCode: String
    /** Name of the airport */
    public var airportName: String
    /** Type of the autocomplete item */
    public var type: FlightType
    /** Name of the city if applicable */
    public var cityName: String?
    /** Display name for the item */
    public var displayName: String?
    /** Name of the country if applicable */
    public var countryName: String?
    /** Country code if applicable */
    public var countryCode: String?
    /** Image URL for the airport or city */
    public var imageUrl: String
    public var coordinates: FlightCoordinate

    public init(iataCode: String, airportName: String, type: FlightType, cityName: String?, displayName: String?, countryName: String?, countryCode: String?, imageUrl: String, coordinates: FlightCoordinate) {
        self.iataCode = iataCode
        self.airportName = airportName
        self.type = type
        self.cityName = cityName
        self.displayName = displayName
        self.countryName = countryName
        self.countryCode = countryCode
        self.imageUrl = imageUrl
        self.coordinates = coordinates
    }


}

