//
// FlightCountryApp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightCountryApp: JSONEncodable {
    public var countryName: String?
    public var appName: String?
    public var deeplinkProviders: String?
    public var isPopupAdsEnabled: Bool?
    public var apiResponseIndex: Int32?
    public var focusTab: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["country_name"] = self.countryName
        nillableDictionary["app_name"] = self.appName
        nillableDictionary["deeplink_providers"] = self.deeplinkProviders
        nillableDictionary["is_popup_ads_enabled"] = self.isPopupAdsEnabled
        nillableDictionary["api_response_index"] = self.apiResponseIndex?.encodeToJSON()
        nillableDictionary["focus_tab"] = self.focusTab?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
