//
// FlightCoordinate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Coordinates of the airport or city */

public struct FlightCoordinate: Codable {

    /** Latitude of the location */
    public var latitude: Double?
    /** Longitude of the location */
    public var longitude: Double?

    public init(latitude: Double?, longitude: Double?) {
        self.latitude = latitude
        self.longitude = longitude
    }


}

