//
// FlightExploreResponseItemLocationModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Location details */

public struct FlightExploreResponseItemLocationModel: Codable {

    /** Entity ID */
    public var entityId: String
    /** Entity name */
    public var name: String
    /** Entity IATA code */
    public var iata: String

    public init(entityId: String, name: String, iata: String) {
        self.entityId = entityId
        self.name = name
        self.iata = iata
    }


}

