//
// FlightPriceInsightRequestCustomDrf.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightPriceInsightRequestCustomDrf: JSONEncodable {
    /** Origin airport code */
    public var origin: String?
    /** Destination airport code */
    public var destination: String?
    /** Departure date in dd-mm-yyyy format */
    public var departure: String?
    /** Whether the trip is round trip */
    public var roundTrip: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["origin"] = self.origin
        nillableDictionary["destination"] = self.destination
        nillableDictionary["departure"] = self.departure
        nillableDictionary["round_trip"] = self.roundTrip
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
