//
// FlightExploreResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightExploreResponseModel: JSONEncodable {
    /** Origin airport IATA code */
    public var origin: String?
    public var currency: FlightCurrencyModelType?
    /** List of countries */
    public var data: [FlightExploreResponseItemModel]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["origin"] = self.origin
        nillableDictionary["currency"] = self.currency?.encodeToJSON()
        nillableDictionary["data"] = self.data?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
