//
// FlightProviderType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightProviderType: JSONEncodable {
    public var isSplit: Bool?
    public var transferType: String?
    public var price: Double?
    public var splitProviders: [FlightSplitProvider]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["isSplit"] = self.isSplit
        nillableDictionary["transferType"] = self.transferType
        nillableDictionary["price"] = self.price
        nillableDictionary["splitProviders"] = self.splitProviders?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
