//
// FlightAlert.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightAlert: Codable {

    public var _id: UUID?
    public var user: FlightAlertUser?
    public var route: FlightAlertRoute?
    public var targetPrice: Int?
    public var isActive: Bool?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(_id: UUID?, user: FlightAlertUser?, route: FlightAlertRoute?, targetPrice: Int?, isActive: Bool?, createdAt: Date?, updatedAt: Date?) {
        self._id = _id
        self.user = user
        self.route = route
        self.targetPrice = targetPrice
        self.isActive = isActive
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case user
        case route
        case targetPrice = "target_price"
        case isActive = "is_active"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }


}

