//
// FlightExploreResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightExploreResponseModel: Codable {

    /** Origin airport IATA code */
    public var origin: String
    public var currency: FlightCurrencyModelType
    /** List of countries */
    public var data: [FlightExploreResponseItemModel]

    public init(origin: String, currency: FlightCurrencyModelType, data: [FlightExploreResponseItemModel]) {
        self.origin = origin
        self.currency = currency
        self.data = data
    }


}

