//
// FlightFlightSearchRequestBodyModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightFlightSearchRequestBodyModel: JSONEncodable {
    /** List of flight legs */
    public var legs: [FlightLegType]?
    /** Cabin class like \&quot;economy\&quot;, \&quot;business\&quot; etc */
    public var cabinClass: String?
    /** Number of adults */
    public var adults: Int32?
    /** List of children ages */
    public var childrenAges: [Int32]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["legs"] = self.legs?.encodeToJSON()
        nillableDictionary["cabin_class"] = self.cabinClass
        nillableDictionary["adults"] = self.adults?.encodeToJSON()
        nillableDictionary["children_ages"] = self.childrenAges?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
