//
// FlightPollRequestBodyModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightPollRequestBodyModel: JSONEncodable {
    public enum FlightSortBy: String { 
        case Duration = "duration"
        case Price = "price"
    }
    public enum FlightSortOrder: String { 
        case Asc = "asc"
        case Desc = "desc"
    }
    /** Maximum duration of the flight in minutes */
    public var durationMax: Int32?
    /** Maximum stop count of the flight */
    public var stopCountMax: Int32?
    /** List of arrival/departure ranges */
    public var arrivalDepartureRanges: [FlightArrivalDeparture]?
    /** List of IATA codes to exclude */
    public var iataCodesExclude: [String]?
    /** List of IATA codes to include */
    public var iataCodesInclude: [String]?
    /** Field to sort by */
    public var sortBy: FlightSortBy?
    /** Order of sorting */
    public var sortOrder: FlightSortOrder?
    /** List of agencies to exclude */
    public var agencyExclude: [String]?
    /** List of agencies to include */
    public var agencyInclude: [String]?
    /** Minimum price for filtering flights */
    public var priceMin: Double?
    /** Maximum price for filtering flights */
    public var priceMax: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["duration_max"] = self.durationMax?.encodeToJSON()
        nillableDictionary["stop_count_max"] = self.stopCountMax?.encodeToJSON()
        nillableDictionary["arrival_departure_ranges"] = self.arrivalDepartureRanges?.encodeToJSON()
        nillableDictionary["iata_codes_exclude"] = self.iataCodesExclude?.encodeToJSON()
        nillableDictionary["iata_codes_include"] = self.iataCodesInclude?.encodeToJSON()
        nillableDictionary["sort_by"] = self.sortBy?.rawValue
        nillableDictionary["sort_order"] = self.sortOrder?.rawValue
        nillableDictionary["agency_exclude"] = self.agencyExclude?.encodeToJSON()
        nillableDictionary["agency_include"] = self.agencyInclude?.encodeToJSON()
        nillableDictionary["price_min"] = self.priceMin
        nillableDictionary["price_max"] = self.priceMax
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
