//
// FlightOriginResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Origin airport details */

public struct FlightOriginResponseModel: Codable {

    public var name: String
    public var shortName: String
    public var cityName: String
    public var latitude: Double
    public var longitude: Double

    public init(name: String, shortName: String, cityName: String, latitude: Double, longitude: Double) {
        self.name = name
        self.shortName = shortName
        self.cityName = cityName
        self.latitude = latitude
        self.longitude = longitude
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case shortName = "short_name"
        case cityName = "city_name"
        case latitude
        case longitude
    }


}

