//
// FlightCountryApp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightCountryApp: Codable {

    public var countryName: String?
    public var appName: String?
    public var deeplinkProviders: String?
    public var isPopupAdsEnabled: Bool?
    public var apiResponseIndex: Int?
    public var focusTab: Int?

    public init(countryName: String?, appName: String?, deeplinkProviders: String?, isPopupAdsEnabled: Bool?, apiResponseIndex: Int?, focusTab: Int?) {
        self.countryName = countryName
        self.appName = appName
        self.deeplinkProviders = deeplinkProviders
        self.isPopupAdsEnabled = isPopupAdsEnabled
        self.apiResponseIndex = apiResponseIndex
        self.focusTab = focusTab
    }

    public enum CodingKeys: String, CodingKey { 
        case countryName = "country_name"
        case appName = "app_name"
        case deeplinkProviders = "deeplink_providers"
        case isPopupAdsEnabled = "is_popup_ads_enabled"
        case apiResponseIndex = "api_response_index"
        case focusTab = "focus_tab"
    }


}

