//
// FlightAirlineFilterData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FlightAirlineFilterData: JSONEncodable {
    public var airlineName: String?
    public var airlineIata: String?
    public var airlineLogo: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["airlineName"] = self.airlineName
        nillableDictionary["airlineIata"] = self.airlineIata
        nillableDictionary["airlineLogo"] = self.airlineLogo
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
