//
// FlightFlightLegModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Outbound flight details */
public class FlightFlightLegModel: JSONEncodable {
    public var origin: FlightAirportModel?
    public var destination: FlightAirportModel?
    public var airline: FlightAirlineModel?
    /** Departure timestamp */
    public var departure: Int32?
    /** Whether the flight is direct */
    public var direct: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["origin"] = self.origin?.encodeToJSON()
        nillableDictionary["destination"] = self.destination?.encodeToJSON()
        nillableDictionary["airline"] = self.airline?.encodeToJSON()
        nillableDictionary["departure"] = self.departure?.encodeToJSON()
        nillableDictionary["direct"] = self.direct
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
