//
// FlightAirportResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Airport details */

public struct FlightAirportResponseModel: Codable {

    public var name: String
    public var shortName: String
    public var popularity: Int
    public var latitude: Double
    public var longitude: Double

    public init(name: String, shortName: String, popularity: Int, latitude: Double, longitude: Double) {
        self.name = name
        self.shortName = shortName
        self.popularity = popularity
        self.latitude = latitude
        self.longitude = longitude
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case shortName = "short_name"
        case popularity
        case latitude
        case longitude
    }


}

