//
// FlightTimeRange.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightTimeRange: Codable {

    public var min: Int?
    public var max: Int?

    public init(min: Int?, max: Int?) {
        self.min = min
        self.max = max
    }


}

