//
// FlightPriceInsightResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FlightPriceInsightResponseModel: Codable {

    public var priceStats: FlightPriceStatsModel
    /** List of price quotes for different dates */
    public var results: [FlightPriceInsightQuoteModel]
    public var currencyInfo: FlightCurrencyModelType?

    public init(priceStats: FlightPriceStatsModel, results: [FlightPriceInsightQuoteModel], currencyInfo: FlightCurrencyModelType?) {
        self.priceStats = priceStats
        self.results = results
        self.currencyInfo = currencyInfo
    }

    public enum CodingKeys: String, CodingKey { 
        case priceStats = "price_stats"
        case results
        case currencyInfo = "currency_info"
    }


}

