//
// GreatCircleDistance.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Distance between departure and arrival */
public class GreatCircleDistance: JSONEncodable {
    public var meter: Double?
    public var km: Double?
    public var mile: Double?
    public var nm: Double?
    public var feet: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["meter"] = self.meter
        nillableDictionary["km"] = self.km
        nillableDictionary["mile"] = self.mile
        nillableDictionary["nm"] = self.nm
        nillableDictionary["feet"] = self.feet
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
