//
// RealtimeFlights.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class RealtimeFlights: JSONEncodable {
    public var id: String?
    public var location: String?
    public var positionSource: String?
    public var callsign: String?
    public var country: String?
    public var lastContact: NSDate?
    public var barometricAltitude: Double?
    public var onGround: Bool?
    public var speed: Double?
    public var direction: Double?
    public var vSpeed: Int32?
    public var altitude: Double?
    public var squawk: String?
    public var specialPurpose: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["location"] = self.location
        nillableDictionary["position_source"] = self.positionSource
        nillableDictionary["callsign"] = self.callsign
        nillableDictionary["country"] = self.country
        nillableDictionary["last_contact"] = self.lastContact?.encodeToJSON()
        nillableDictionary["barometric_altitude"] = self.barometricAltitude
        nillableDictionary["on_ground"] = self.onGround
        nillableDictionary["speed"] = self.speed
        nillableDictionary["direction"] = self.direction
        nillableDictionary["v_speed"] = self.vSpeed?.encodeToJSON()
        nillableDictionary["altitude"] = self.altitude
        nillableDictionary["squawk"] = self.squawk
        nillableDictionary["special_purpose"] = self.specialPurpose
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
