//
// ScheduleListAirlineType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Airline information  */
public class ScheduleListAirlineType: JSONEncodable {
    public var name: String?
    public var iataCode: String?
    public var icaoCode: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["iata_code"] = self.iataCode
        nillableDictionary["icao_code"] = self.icaoCode
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
