//
// ScheduleResultModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ScheduleResultModel: JSONEncodable {
    public var airline: ScheduleListAirlineType?
    /** Flight number */
    public var flightNumber: String?
    /** Flight status */
    public var status: String?
    /** Operated by for codeshares */
    public var operatedBy: String?
    /** Departure time */
    public var departureTime: String?
    /** Arrival time */
    public var arrivalTime: String?
    public var airport: ScheduleListAirportType?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["airline"] = self.airline?.encodeToJSON()
        nillableDictionary["flight_number"] = self.flightNumber
        nillableDictionary["status"] = self.status
        nillableDictionary["operated_by"] = self.operatedBy
        nillableDictionary["departure_time"] = self.departureTime
        nillableDictionary["arrival_time"] = self.arrivalTime
        nillableDictionary["airport"] = self.airport?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
