//
// ScheduleResponseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ScheduleResponseModel: JSONEncodable {
    public var departureAirport: ScheduleListAirportType?
    public var arrivalAirport: ScheduleListAirportType?
    /** List of schedule results */
    public var results: [ScheduleResultModel]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["departure_airport"] = self.departureAirport?.encodeToJSON()
        nillableDictionary["arrival_airport"] = self.arrivalAirport?.encodeToJSON()
        nillableDictionary["results"] = self.results?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
