//
// ScheduleListAirportType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Departure airport */
public class ScheduleListAirportType: JSONEncodable {
    public var iataCode: String?
    public var icaoCode: String?
    public var name: String?
    public var city: String?
    public var timezone: Timezone?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["iata_code"] = self.iataCode
        nillableDictionary["icao_code"] = self.icaoCode
        nillableDictionary["name"] = self.name
        nillableDictionary["city"] = self.city
        nillableDictionary["timezone"] = self.timezone?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
