//
// Timezone.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Timezone: JSONEncodable {
    public var timezone: String?
    public var countryCode: String?
    public var gmt: Double?
    public var dst: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["timezone"] = self.timezone
        nillableDictionary["country_code"] = self.countryCode
        nillableDictionary["gmt"] = self.gmt
        nillableDictionary["dst"] = self.dst
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
