//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class User: JSONEncodable {
    public enum Os: String { 
        case Ios = "ios"
        case Android = "android"
    }
    public var userId: String?
    public var pushToken: String?
    public var transactionId: String?
    public var os: Os?
    public var alert: Bool?
    public var remainder: Bool?
    public var isPremium: Bool?
    public var trackCount: Int32?
    public var detailsCount: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["user_id"] = self.userId
        nillableDictionary["push_token"] = self.pushToken
        nillableDictionary["transaction_id"] = self.transactionId
        nillableDictionary["os"] = self.os?.rawValue
        nillableDictionary["alert"] = self.alert
        nillableDictionary["remainder"] = self.remainder
        nillableDictionary["is_premium"] = self.isPremium
        nillableDictionary["track_count"] = self.trackCount?.encodeToJSON()
        nillableDictionary["details_count"] = self.detailsCount?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
